website1: 'https://test-stand.gb.ru/gateway/login'
website2: 'https://test-stand.gb.ru/api/posts'
#username: 'Maria_G'
#password: 'b61aa5326f'

#username: 'Konstantin_Or'
#password: 'cb920a7fff'
#token: "a897b8d1bb157716529bcf03bddf3f00"

username: 'Antonio_L'
password: 'da9685aeca'

